version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./mdata:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: putyournotes
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo